# Until a lock file exists for Hatch, all dependencies are gonna be pinned here

[envs.default]
skip-install = true
dependencies = [
	"aiohttp==3.7.3",
	"aiosqlite==0.16.0",
	"discord.py[voice]==1.7.3",
	"setuptools==57.1.0",  # yoyo-migrations needs it but didn't declare it :/
	"simpleeval==0.9.10",
	"soundit==0.2.1",
	"yoyo-migrations==7.3.2",
	"yt-dlp==2021.9.2",
	# Pinned sub-dependencies
	"async-timeout==3.0.1",
	"attrs==20.3.0",
	"cffi==1.14.5",
	"chardet==3.0.4",
	"idna==3.1",
	"multidict==5.1.0",
	"mutagen==1.45.1",
	"pycparser==2.20",
	"pycryptodome==3.10.1",
	"PyNaCl==1.4.0",
	"six==1.15.0",
	"sqlparse==0.4.1",
	"tabulate==0.8.7",
	"typing-extensions==4.0.0",
	"websockets==9.1",
	"yarl==1.6.3",
]

[envs.os]
extra-dependencies = [
	"httpx==0.22.0",
	"pure-protobuf==2.1.0",
	# Pinned sub-dependencies
	"anyio==3.5.0",
	"certifi==2021.10.8",
	"charset-normalizer==2.0.12",
	"h11==0.12.0",
	"httpcore==0.14.7",
	"idna==3.1",  # Duplicated sub-dependency but eh
	"rfc3986==1.5.0",
	"sniffio==1.2.0",
]

[envs.two]
# This is for discord.py v2.x. Also contains the os env dependencies.
dependencies = [
	"aiohttp==3.8.3",
	"aiosqlite==0.16.0",
	"av==10.0.0",
	"discord.py[voice]==2.2.2",
	"croniter==1.3.4",
	"httpx==0.22.0",
	"pure-protobuf==2.1.0",
	"python-dateutil==2.8.2",
	"setuptools==57.1.0",  # yoyo-migrations needs it but didn't declare it :/
	"simpleeval==0.9.10",
	"soundit==0.2.1",
	"yoyo-migrations==7.3.2",
	"yt-dlp==2023.2.17",
	# Pinned sub-dependencies
	"aiosignal==1.3.1",
	"anyio==3.5.0",
	"async-timeout==4.0.2",
	"attrs==20.3.0",
	"brotli==1.0.9",
	"certifi==2021.10.8",
	"cffi==1.14.5",
	"chardet==3.0.4",
	"charset-normalizer==2.1.1",
	"frozenlist==1.3.3",
	"h11==0.12.0",
	"httpcore==0.14.7",
	"idna==3.1",
	"multidict==5.1.0",
	"mutagen==1.45.1",
	"pycparser==2.20",
	"pycryptodome==3.17",
	"PyNaCl==1.4.0",
	"rfc3986==1.5.0",
	"six==1.15.0",
	"sniffio==1.2.0",
	"sqlparse==0.4.1",
	"tabulate==0.8.7",
	"typing-extensions==4.0.0",
	"websockets==9.1",
	"yarl==1.6.3",
]
