# If you don't have Hatch, you can still pip install from the requirements.txt

[env]
requires = ["hatch-pip-compile"]

[envs.default]
skip-install = true
type = "pip-compile"
dependencies = [
	"aiohttp",
	"aiosqlite",
	"discord.py[voice]",
	"setuptools",  # yoyo-migrations needs it but didn't declare it :/
	"simpleeval>=0.9.11",  # Earliest version that works with setuptools>=58
	"soundit",
	"yoyo-migrations",
	"yt-dlp",
]

[envs.os]
lock-filename = "requirements-os.txt"
pip-compile-constraint = "default"
extra-dependencies = [
	"av",
	"httpx",
	"numpy",
	"pure-protobuf<3",
]
